services:
  - type: web
    name: Portafolio-Back-End-SC30
    env: docker
    region: oregon
    plan: starter
    envVars:
      - key: MAIL_USER
        value: seruhiocode30@gmail.com
      - key: MAIL_PASS
        sync: false
      - key: RESEND_API_KEY
        sync: false
